### ISSUE TITLE
Color mods in .sublime-color-scheme

### ISSUE THREAD

**Issue by blake-regalia** [facelessuser/ExportHtml#67] opened 2020-01-01 03:11 UTC
## Description

Support color mods with variables.

## Steps to Reproduce Issue

Any rule that uses color mod with variable references is not making it to the HTML document. It seems this case is not captured by the `COLOR_MOD_RE` regexp nor subsequently in the handler function.

`example.sublime-color-scheme`:
```
{
    "name": "Example",
    "variables": {
        "root": "hsl(199, 56%, 73%)"
    },
    "globals": {
        "foreground": "#bebbb0",
        "background": "#252525"
    },
    "rules": [
        {
            "scope": "storage.type",
            "foreground": "color(var(root) blend(#000 20% hsl))"
        },
        {
            "scope": "constant",
            "foreground": "#22dd00"
        }
    ]
}
```

How it appears in ST3:
![ST3](https://user-images.githubusercontent.com/1456400/71639538-47531880-2c2d-11ea-997e-3c581fa3ec8e.png)

How it appears in exported HTML:
![ExportHtml](https://user-images.githubusercontent.com/1456400/71639541-4a4e0900-2c2d-11ea-9e1b-81ddca042f13.png)

And the generated HTML:
```html
<table cellspacing="0" cellpadding="0" class="code_page">
    <tbody>
        <tr>
            <td valign="top" id="L_0_1" class="code_text code_gutter" style="background: #252525">
                <span style="color: #BEBBB0;">&nbsp;1&nbsp;</span>
            </td>
            <td valign="top" class="code_text code_line" style="background-color: #252525;">
                <div id="C_0_1">
                    <span class=" real_text" style="background-color: #252525; color: #BEBBB0;">int</span>
                    <span class=" real_text" style="background-color: #252525; color: #BEBBB0;"> i </span>
                    <span class=" real_text" style="background-color: #252525; color: #BEBBB0;">=</span>
                    <span class=" real_text" style="background-color: #252525; color: #BEBBB0;"> </span>
                    <span class=" real_text" style="background-color: #252525; color: #22DD00;">0</span>
                    <span class=" real_text" style="background-color: #252525; color: #BEBBB0;">;</span>
                </div>
            </td>
        </tr>
    </tbody>
</table>
```

**Comment by facelessuser** [comment] 2020-01-01 03:29
Can you give me actual working example of a color scheme?  This line is all messed up:

```
"foreground": "color(var(root) blend(#000 20% hsl)"
```

1. Please create an example that has proper **valid** syntax.
2. Test if **that** example works.

Once these conditions are met, I will look into this further.

**Comment by facelessuser** [comment] 2020-01-01 03:30
@gir-bot  add S: needs-more-info
@gir-bot remove S: triage

**Comment by facelessuser** [comment] 2020-01-01 03:31
Whoops

@gir-bot add S: more-info-needed

**Comment by blake-regalia** [comment] 2020-01-01 08:32
@facelessuser the example was just a typo missing a closing paren. See updated comment. Thanks

**Comment by facelessuser** [comment] 2020-01-01 09:11
Are you sure? What's the trailing hsl doing?

**Comment by facelessuser** [comment] 2020-01-01 15:09
Hmm, looking through Sublime documentation, I now see that giving blend hsl blends in the hsl color space. I feel this is new, out newly documented from when I supported such things.

If your remove the trailing hsl, does it work?

**Comment by facelessuser** [comment] 2020-01-01 15:17
So, I just tried your example with blending, but removing the hsl color space requirement, and then it works fine. So it appears that ExportHTML does not support blending in the hsl color space.

So, basically, we just need to add HSL color space blending. Color mod itself seems to work fine,

@gir-bot lgtm
@gir-bot add T: bug, S: confirmed

**Comment by facelessuser** [comment] 2020-01-01 17:29
Going to need to figure out a good algorithm to blend hsl colors. You can't use the rgba algorithm and get the proper color, but that may be an okay workaround to get something that doesn't fail, even if it is wrong.

If you are familiar with proper hsl blending algorithms, and can point me at one, that may help.

**Comment by blake-regalia** [comment] 2020-01-01 19:52
Here's an implementation in JavaScript: https://github.com/jonathantneal/postcss-color-mod-function/blob/master/lib/color.js#L166

**Comment by facelessuser** [comment] 2020-01-01 20:03
Perfect. That's what we need :slightly_smiling_face:

**Comment by facelessuser** [comment] 2020-01-02 04:31
It seems the referenced algorithm has a very permissible license, so if we need to port it directly, it should be safe...and probably the easiest path.

The proper approach is also loosely described in the CSS spec as well. https://www.w3.org/TR/2016/WD-css-color-4-20160705/#funcdef-color-mod. So we may not need to directly copy the algorithm from another project, but it's nice to know it's there if we need to use it.

Seems like we should just go ahead and add recognition for rgb, hsl, and hwb color space specifiers. I don't know if Sublime's color mod explicitly supports all these, but I'd rather support them and not have to worry about it later.

**Comment by facelessuser** [comment] 2020-01-11 19:47
Going over the color mod spec, it seems like all the channels are still evaluated in a linear fashion. The only difference with hsl and hwb is that you have to be aware of when the angle between the two hues is greater than 180 degrees. When this occurs, we simply need to evaluate the blend where the angle is smallest.

I have it partially working locally, so I should have something cobbled together soon.

**Comment by facelessuser** [comment] 2020-01-12 01:57
I think we have a good fix. Your example now works as expected:

![chrome_FGJLJNK01w](https://user-images.githubusercontent.com/1055125/72212969-1207bf80-34a4-11ea-997e-cbcb4f202631.png)

I will most likely do a bit more testing as this change will need to get pushed to a couple of my other repos, but hopefully we'll have it validated and a release out within the week.

**Comment by blake-regalia** [comment] 2020-01-12 18:52
Thanks for awesome work! Trying it out, I notice the color scheme comes out with very different saturation than how it looks in ST3. I see that `percent_blend_channel` multiplies the factors against the opposite color values `(c1 * f + c2 * (1 - f))`, which yields the complement lightness and complement saturation values of what it should (compare to reference implementation).

For example, starting with a base HSL color having saturation 90%, then blending with an HSL color having saturation 14% and a blend factor of 20%:
`c1 = 0.9; c2 = 0.14; f = 0.2;`
currently: `(c1 * f + c2 * (1 - f))` yields ~29.2%
opposite: `(c1 * (1 - f) + c2 * f)` yields ~74.8%

**Comment by facelessuser** [comment] 2020-01-12 20:55
@blake-regalia I've currently been working through this issue before I even saw your post.

There appears to be a very weird situation here. I can consistently get the hue with some of my recent fixes. but it appears the c1 and c2 are flipped in Sublime depending on some unknown factor. I'm not sure Sublime has implemented it correctly to be honest. I'll post some details in a bit.

**Comment by facelessuser** [comment] 2020-01-12 21:31
@blake-regalia, I have a branch here that fixes hue issues: https://github.com/facelessuser/ExportHtml/tree/blend-fix. We where also incorrectly triggering hwb which is fixed as well. I think this branch implements things correctly, but with that said Sublime deviates in one corner case that makes no sense:

In the branch, the following works as expected:

`color(#000 blend(hsl(199, 56%, 73%) 70% hsl))` Gives us visually what we expect as does `color(#000 blend(hsl(199, 56%, 73%) 20% hsl))`

But when we switch the base color with the color to be blended:

Both `color(#000 blend(hsl(199, 56%, 73%) 70% hsl))` and `color(#000 blend(hsl(199, 56%, 73%) 20% hsl))` seem to handle saturation and luminescence in the opposite order.

**Comment by facelessuser** [comment] 2020-01-12 21:35
Maybe I'm missing something? If you have any insight, I'd love to here. From my understanding, as we approach 100% we approach the base color. So `color(#000 blend(hsl(199, 56%, 73%) 70% hsl))` should favor the saturation, luminescence, and hue of `#000`, which it does in the given branch.

But for some reason `color(hsl(199, 56%, 73%) blend(#000 70% hsl)` favors the hue of the `hsl` color, but then favors the luminescence and saturation of `#000`, while implementation does not.

**Comment by facelessuser** [comment] 2020-01-12 21:36
It's almost as if Sublime is favoring the darker color first when evaluating the `l` and `s` components....while we are favoring the base color.

**Comment by facelessuser** [comment] 2020-01-12 21:52
I may end up merging the current fix even though it doesn't match Sublime in the above mentioned corner case to fix some of the regressions I introduced. I've sent out a question on Sublime's discord to try and better understand why Sublime is flipping saturation logic depending on the color attributes.

**Comment by facelessuser** [comment] 2020-01-12 22:12
I've gone ahead and released 2.14.1. I feel like the recent fixes are following the CSS spec, but it does seem to differ from Sublime when a lighter color is used as the base color. But again, I think we are doing what *should* be done. I'm leaving this issue open as I work with the Sublime devs to see why this discrepancy exists.

It is possible I am simply wrong...but I'd love to have this explained so I can understand how.

**Comment by facelessuser** [comment] 2020-01-13 00:31
I'm also suspicious that Sublime is blending the hue channel in the wrong direction. Apparently, to get hues to blend proper, I have to take the factor and use `f = 1.0 - f`. On `r`, `g`, `b` channels is this is not needed and the base is fed in as `c1`. But with hue, you have to either flip `c1` and `c2`, or adjust the factor. I originally though this was need for just when the angles exceeded 180. But thinking about this more, and running some more tests, it appears Sublime requires me to adjust the factor on all hues. Hues seem reversed from what I would expect.

I suspect not much testing has been done by Sublime as far as HSL color space blending is concerned.

**Comment by facelessuser** [comment] 2020-01-13 02:57
Okay, the 2.14.3 release is as close as we can get to Sublime without clarification from Sublime. We now:

- Force reverse blending logic for all hue cases. Not sure why every other channel blends proper with one direction, but Hue requires the reverse direction 🤷‍♂ .
- We cannot properly blend saturation and luminescence consistently. Sublime seems blending logic seems to flip blending direction depending on whether a darker color is the base or the blending color. We are currently blending in what we presume is the proper direction as we do with the red, green, and blue channel in RGB mode. Reversing logic in RGB starts throwing off colors, so I am positive we are using the correct blend direction with RGB.

I am almost positive that both these cases are wrong in Sublime's implementation, but I can at least fully mimic the first. The second is impossible without me fully understanding the specifics that Sublime is using, and personally, I'd prefer they fix this behavior to be consistent, even if they pick the backwards direction of hue.

**Comment by blake-regalia** [comment] 2020-01-13 05:48
I just tried previewing parts of [our color scheme](https://github.com/blake-regalia/linked-data.syntaxes/blob/build/build/sublime/assets/macaron-dark.sublime-color-scheme) using [postcss-color-mod-function](https://github.com/jonathantneal/postcss-color-mod-function) and unfortunately all three renders look different (postcss' impl, the latest release of ExportHtml, and ST3). I too am suspicious that ST3's impl is wrong, and am wondering if postcss' is the most correct version (of an abandoned spec draft 🙄).

**Comment by facelessuser** [comment] 2020-01-13 06:08
Yeah, I haven't compared to postcss, but as far as I can tell, this if I removed this part here: https://github.com/facelessuser/ExportHtml/blob/master/lib/rgba.py#L52, I think I'd be following the spec.  The channels should be evaluated in a linear fashion no different that the RGB channels are handled. Hue is a little different because you evaluate between the angle either clockwise or counter clockwise depending if you are under or over 180 degrees in difference. This is easy to accommodate for, and once you do, it should resolve no different than other channels.

But, yeah, it would be nice to have a one true comparison to be 100% sure. I didn't look too close at the postcss implementation, but I don't think I recall them accounting for the 180 degree clockwise and counter clockwise logic. Maybe I didn't look to close 🤷‍♂ .

**Comment by facelessuser** [comment] 2020-01-17 19:35
I have filed a bug with Sublime Text explaining what **I** think it should be doing. We shall see what their response is if/when they get around to looking at the issue.

https://github.com/sublimehq/sublime_text/issues/3176

**Comment by facelessuser** [comment] 2020-03-03 15:32
Seems like there will be some fixed coming in Sublime. It sounds like hue was reversed, and the saturation and luminescence channel were incorrectly going through Sublime's hue logic (which would cause the base and and mixin color to get swapped sometimes) causing the colors to sometimes get blended in the wrong direction.

It **sounds** like all we have to do once the fix drops in a Sublime build is to remove our hue workaround. The other channels should start working without us doing anything else. I'll have to verify once the fix releases.

**Comment by facelessuser** [comment] 2020-03-27 18:35
Supposedly this is fixed in the latest Sublime. I will need to revert our workaround and test again.

**Comment by blake-regalia** [comment] 2020-03-27 19:25
Great! Sounds like it will be part of breaking change anyway so hopefully we can tag it as a separate release and PR [repository/e.json](https://github.com/wbond/package_control_channel/blob/master/repository/e.json#L1614) so the workaround will still apply for users on `>=3000 <4000`.

**Comment by facelessuser** [comment] 2020-03-28 14:03
I have no plans for a separate release. Package Control is planned to allow differentiation in the future for st3 and st4, much like how one dependency can specify sub folders for specific architectures and platforms (i.e. Linux vs Windows etc.). I will wait for that. In the short term, we will just use a feature switch:

```
HSL_WORKAROUND = int(sublime.version()) < 4069
```

**Comment by facelessuser** [comment] 2020-03-28 14:05
Another small note, Sublime doesn't support `turn`, `rad`, `grad` units in `HSL`. Nor does this package either...I mean now it will, because now I'm aware of it, but this is just in case Sublime one day supports it. I don't think they care, and will probably always require `deg` units, but one last thing I'll have to worry about in the future.

**Comment by facelessuser** [comment] 2020-03-28 14:21
I just tested removal of workaround on Sublime 4069, and it looks like they took all my comments to heart. I had to change your original example to use 80% mix because Sublime used to blend hue backwards, so now Sublime and and ExportHtml are in alignment:

```js
{
    "name": "Example",
    "variables": {
        "root": "hsl(199, 56%, 73%)"
    },
    "globals": {
        "foreground": "#bebbb0",
        "background": "#252525"
    },
    "rules": [
        {
            "scope": "storage.type",
            "foreground": "color(var(root) blend(#000 80% hsl))"
        },
        {
            "scope": "constant",
            "foreground": "#22dd00"
        }
    ]
}
```

Sublime

<img width="129" alt="sublime_text_84g4JE7R5O" src="https://user-images.githubusercontent.com/1055125/77825121-df498c80-70cc-11ea-9d0c-b4f379c3e8ce.png">

Export HTML

<img width="295" alt="chrome_RaRHS5dfme" src="https://user-images.githubusercontent.com/1055125/77825144-0bfda400-70cd-11ea-9fea-9a0b36a36d6e.png">

**Closed** 2020-03-29 00:51 UTC
Labels: S: confirmed, T: bug
